### ISSUE TITLE
Can run activity?

### ISSUE THREAD

**Issue by lordmen99** [75py/Android-OverlayViewManager#1]
Interest use this library, but its can start activity with overlayview? example, i add videocall in overlayview then do other task in same screen.

**Comment by 75py** [comment]
@lordmen99 Thank you for your comment!

I'm not good at English...
Do you want to show some android.view.View(videocall) with OverlayView, and start an Activity screen onClick the views. 
Correct?

The lifecycle of OverlayView is depends on the parent Activity or Service.
[Sample1Activity.java](https://github.com/75py/Android-OverlayViewManager/blob/master/sample/src/main/java/com/nagopy/android/overlayviewmanager/sample/Sample1Activity.java) or [SampleAllOptionsActivity.java](https://github.com/75py/Android-OverlayViewManager/blob/master/sample/src/main/java/com/nagopy/android/overlayviewmanager/sample/SampleAllOptionsActivity.java) are samples of Activity's one.
If you want to show OverlayView without depending on some Activity screen, you should implement android.app.Service and use OverlayView instance.
I'll add the sample code for Service class.

And, OverlayView can get click events.
See that.
- OverlayView#setClickable
- OverlayView#setOnClickListener

Did I answer your questions?

**Comment by lordmen99** [comment]
yes, actualy i plan add with this app https://github.com/AgoraIO/OpenLive-Android

its live streaming app,i want when user example backpress its will make live streaming screen in overlay. and can do other task over that live streaming screen, when tap again to live streaming screen will be back in live streaming activity. thats it

**Comment by 75py** [comment]
@lordmen99 I added a sample code. See [Sample2Activity.java](https://github.com/75py/Android-OverlayViewManager/blob/master/sample/src/main/java/com/nagopy/android/overlayviewmanager/sample/Sample2Activity.java)

<img src="https://user-images.githubusercontent.com/3153211/32987734-0e8a0808-cd37-11e7-9138-0fd8c24760af.gif" width="270" height="480" alt="">
